language: ruby

sudo: false

addons:
  postgresql: "9.4"

services:
  - postgresql

rvm:
  - 2.2.4

install:
  - "travis_retry bundle config build.nokogiri --use-system-libraries"
  - "travis_retry bundle install --retry 3"

before_script:
  - psql -c 'create database wechat_starter_test;' -U postgres
  - bundle exec rake db:migrate --trace

script: bundle exec rake
