default: &default
  appid:  <%= Figaro.env.wechat_app_id %>
  secret: <%= Figaro.env.wechat_secret %>
  token:  <%= Figaro.env.wechat_token %>

production:
  <<: *default
  encoding_aes_key: <%= Figaro.env.wechat_encoding_aes_key %>
  encrypt_mode: true

development:
  <<: *default
  encoding_aes_key: <%= Figaro.env.wechat_encoding_aes_key %>
  encrypt_mode: true

test:
  <<: *default
